export type compoundName = 'alkanes'
  | 'cycloalkanes'
  | 'alkenes'
  | 'alkynes'
  | 'arenes'
  | 'alcohols'
  | 'phenols'
  | 'aldehydes_ketones'
  | 'carboxylicAcids'
  | 'esters'
  | 'carbohydrates'
  | 'amines'
  | 'amino_acids'